spring.application.name=haisclinic-app-backend

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/haisclinic}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:haisclinic}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:haisclinic}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:5MB}

app.storage.images-dir=${APP_STORAGE_IMAGES_DIR:uploads/images}
